name: analog_clock
description: Analog clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.3
  device_preview: ^0.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf

    - family: Montserrat Alternates
      fonts:
        - asset: assets/fonts/MontserratAlternates/MontserratAlternates-Regular.ttf
        - asset: assets/fonts/MontserratAlternates/MontserratAlternates-Bold.ttf

    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen/Oxygen-Regular.ttf
        - asset: assets/fonts/Oxygen/Oxygen-Bold.ttf



